version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: runner
    ports:
      - "3000:3000"
      - "4111:4111"
    volumes:
      - ./src:/app/src
      - ./public:/app/public
    tmpfs:
      - /app/.next
      - /app/.mastra
      - /tmp
    env_file:
      - .env.local
      - .env.development
    depends_on:
      - db
    # メモリ制限を設定
    deploy:
      resources:
        limits:
          memory: 2G
    environment:
      # Node.jsのメモリ制限
      NODE_OPTIONS: "--max-old-space-size=1536"

  # ローカル開発用のデータベース（SQLite代替として）
  db:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: camera_app
    volumes:
      - postgres_data:/var/lib/postgresql/data
    # リソース制限を追加
    deploy:
      resources:
        limits:
          memory: 512M

volumes:
  postgres_data:
